import type { Metadata } from "next";

import React from 'react'

export const metadata: Metadata = {
    title: "My Schedule - Framework",
    description: "Generated by create next app",
};

import FrameworkLayout from "@/components/dashboard/proyek/framework/FrameworkLayout";

export default function page() {
    return (
        <FrameworkLayout />
    )
}
