import type { Metadata } from "next";

import React from 'react'

export const metadata: Metadata = {
    title: "My Schedule - Proyek",
    description: "Generated by create next app",
};

import ProyekLayout from "@/components/dashboard/proyek/proyek/ProyekLayout";

export default function page() {
    return (
        <ProyekLayout />
    )
}
