import type { Metadata } from "next";

import React from 'react'

import ProfileLayout from "@/components/dashboard/profile/ProfileLayout"

export const metadata: Metadata = {
    title: "My Schedule - Profile",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <ProfileLayout />
    )
}
