import type { Metadata } from "next";

import React from "react";

export const metadata: Metadata = {
  title: "Management Accounts - Home",
  description: "Generated by create next app",
};

import ManagementAccountsLayout from "@/components/dashboard/management-accounts/home/ManagementAccountsLayout";

export default function page() {
  return <ManagementAccountsLayout />;
}
