import type { Metadata } from "next";

import React from 'react'

export const metadata: Metadata = {
    title: "My Schedule - Category",
    description: "Generated by create next app",
};

import CategoryLayout from "@/components/dashboard/proyek/category/CategoryLayout"

export default function page() {
    return (
        <CategoryLayout />
    )
}
